### ISSUE TITLE
4-up view behaviors checklist

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Asteroid-Zoo#30]
- [x] Users should be able to make marks on any frame without having to select it with the slider
- [x] Clicking inside a frame should automatically select it in the checklist on the right, and (possibly) move the slider accordingly
- [x] Users should not be able to move marks from frames they are not placed on (the dimmed ones)
- [x] When a user clicks cancel the marks for the current asteroid should be removed: (issue #17)

Discussion:
- Should the slider completely disappear in the 4-up view--or just move to the correct when you click on a frame (in a disabled state)?
- Should marks be visible on all frames (dimmed) to show alignment / tracking, or only visible on the frame they are placed on?

Feel free to add more to this list
