### ISSUE TITLE
(Friday coding marathon) Todo before beta launch

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/Asteroid-Zoo#77]
Higher priority:
- [x] Cache images: There's a lag every time a new subject is loaded (not caching properly?)
- [x] Fix known asteroid feedback
- [x] Resolve cross origin issues
- [x] Fix image invert

Lower priority:
- [x] Handle subjects with less than 3 images
- [ ] Handle images that are less than 256x256 (align top-left with black background?)

Final touches:
- [x] code cleanup (remove unused dependencies, etc.)
- [ ] final test (see "Test Against Ground Truth Data")
